apiVersion: v1
kind: Service
metadata:
  name: fl-server
spec:
  type: NodePort
  selector:
    app: fl-server
  ports:
    - name: gradio
      port: 7860
      targetPort: 7860
      nodePort: 30000
    - name: metrics
      port: 8000
      targetPort: 8000
      nodePort: 30001
